language: go

sudo: false

go:
  - 1.8

default:  
  - go build $$(go list ./... | grep -v /vendor/)

before_script:
  - go fmt ./...
  - go vet $(go list ./...)

test:
  - go test -v -race $$(go list ./... | grep -v /vendor/ | grep -v /cmd/)
  - sh testCoverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) -t e8c7199e-c200-4dc4-af38-36e85163a61a