language: go

sudo: false

go:
  - 1.6

default:  
  go build ./...

before_script:
  go fmt ./...
  go vet $(go list ./...)

test:
  go test -v -race $$(go list ./... | grep -v /vendor/ | grep -v
  sh testCoverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)